CREATE DATABASE Practice

USE Practice

CREATE TABLE Passports(
	[PassportID] INT PRIMARY KEY IDENTITY(101, 1) NOT NULL,
	[PassportNumber] NVARCHAR(30) NOT NULL
)

CREATE TABLE Persons(
	[PersonID] INT PRIMARY KEY IDENTITY NOT NULL,
	[FirstName] NVARCHAR(20) NOT NULL,
	[Salary] DECIMAL(7,2),
	[PassportID] INT FOREIGN KEY REFERENCES Passports([PassportID])
)

INSERT INTO Passports
VALUES
('N34FG21B'),
('K65LO4R7'),
('ZE657QP2')

INSERT INTO Persons
VALUES
('Roberto', 43300.00, 102),
('Tom', 56100.00, 103),
('Yana', 60200.00, 101)